module.exports = {
  ERRORS: {
    ERR_WHEN_INIT_SDK: 'ERR_WHEN_INIT_SDK',
    ERR_INIT_SDK_LOST_CONFIG: 'ERR_INIT_SDK_LOST_CONFIG',
    ERR_WHEN_INIT_MYSQL: 'ERR_WHEN_INIT_MYSQL',
    DBERR: {
      ERR_WHEN_INSERT_TO_DB: 'ERR_WHEN_INSERT_TO_DB',
      ERR_NO_SKEY_ON_CALL_GETUSERINFOFUNCTION:
        'ERR_NO_SKEY_ON_CALL_GETUSERINFOFUNCTION',
      ERR_NO_OPENID_ON_CALL_GETUSERINFOFUNCTION:
        'ERR_NO_OPENID_ON_CALL_GETUSERINFOFUNCTION'
    },

    // 认证错误
    ERR_HEADER_MISSED: 'ERR_HEADER_MISSED',
    ERR_IN_DECRYPT_DATA: 'ERR_IN_DECRYPT_DATA',
    ERR_SKEY_INVALID: 'ERR_SKEY_INVALID'
  },
  LOGIN_STATE: {
    SUCCESS: 1, // 登陆成功
    FAILED: 0 // 登录失败
  }
};
